title: Paladins Developers
description: A list of resources and packages for developers using the Hi-Rez Paladins API.
show_downloads: true
google_analytics: UA-91457849-5
theme: jekyll-theme-midnight
